version: "3.9"

services:
  web:
    build: .
    image: bibl_web:latest
    container_name: bibl_app
#    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - bibl_static_volume:/app/staticfiles
      # - media_volume:/app/mediafiles # Если используете
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:18.1
    container_name: bibl_db
    restart: always
    env_file:
      - .env
    volumes:
      - bibl_postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"

  nginx:
    image: nginx:1.26.1-alpine
    container_name: bibl_nginx
    ports:
      - "80:80"
    volumes:
      - bibl_static_volume:/usr/share/nginx/html/static
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  bibl_postgres_data:
  bibl_static_volume: